const mockArray = [1,2,3,4,5,6,7,8,9,10];
const mockCollections = {
  1: {
    "id": 1,
    "name": "Hello",
    "description": "Hello 1234 this is David",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  },
  2: {
    "id": 2,
    "name": "Goodbye",
    "description": "I will never give you up",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  },
  3: {
    "id": 3,
    "name": "Party",
    "description": "In the USA",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": true,
    "email_notification": false,
    "push_notification": false,
  },
  4: {
    "id": 4,
    "name": "Taylor Swift",
    "description": "I knew you were trouble",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": true,
    "email_notification": false,
    "push_notification": false,
  },
  5: {
    "id": 5,
    "name": "Something",
    "description": "Just like this",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  },
  6: {
    "id": 6,
    "name": "Shelter",
    "description": "Porter Robinson",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": true,
    "email_notification": false,
    "push_notification": false,
  },
  7: {
    "id": 7,
    "name": "Mirrors",
    "description": "I don't want to lose you now",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  },
  8: {
    "id": 8,
    "name": "Umbrella",
    "description": "ella ella ella ehhhh",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  },
  9: {
    "id": 9,
    "name": "AND HIS NAME",
    "description": "IS JOHN CENA",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  },
  10: {
    "id": 10,
    "name": "The Walking Wounded",
    "description": "Nicky",
    "created_at": "May",
    "updated_at": "May",
    "is_subscribed": false,
    "email_notification": false,
    "push_notification": false,
  }
};
export { mockArray, mockCollections };
